import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#0a0a0a',
  '--slot4-page-text': '#eae8e8',
  '--slot4-panel-bg': '#0b0e19',
  '--slot4-surface-bg': '#101421',
  '--slot4-muted-text': '#a7a7ad',
  '--slot4-soft-muted-text': '#747783',
  '--slot4-accent': '#0e54f1',
  '--slot4-accent-fill': '#0e54f1',
  '--slot4-accent-soft': 'rgba(14,84,241,0.16)',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#050505',
  '--slot4-dark-text': '#fefefe',
  '--slot4-media-bg': '#151927',
  '--slot4-cream': '#f4f5f7',
  '--slot4-warm': '#0f1320',
  '--slot4-lavender': '#11182b',
  '--slot4-gray': '#151515',
  '--slot4-body-gradient': 'radial-gradient(circle at 50% 10%, rgba(14,84,241,0.26), transparent 34%), #0a0a0a',
  '--editable-page-bg': '#0a0a0a',
  '--editable-page-text': '#eae8e8',
  '--editable-container': '1360px',
  '--editable-border': 'rgba(255,255,255,0.12)',
  '--editable-nav-bg': '#050505',
  '--editable-nav-text': '#fefefe',
  '--editable-nav-active': '#0e54f1',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#0e54f1',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#101421',
  '--editable-footer-bg': '#050505',
  '--editable-footer-text': '#eae8e8',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-none',
  shadowStrong: 'shadow-[0_4px_20px_rgba(0,0,0,0.22)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.04),rgba(0,0,0,0.82))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-10',
    sectionY: 'py-20 sm:py-24 lg:py-[120px]',
  },
  layout: {
    safeGrid: 'grid gap-5 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[260px] shrink-0 snap-start sm:w-[320px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.18em] text-[var(--slot4-accent)]',
    heroTitle: 'text-5xl font-bold leading-[1.02] tracking-[-0.02em] sm:text-7xl lg:text-[80px]',
    sectionTitle: 'text-4xl font-semibold leading-[1.12] tracking-[-0.01em] sm:text-5xl',
    body: 'text-base leading-[1.5]',
    emphasis: 'font-semibold italic text-[var(--slot4-page-text)]',
  },
  surface: {
    card: `rounded-[16px] border ${editablePalette.border} ${editablePalette.surfaceBg}`,
    soft: `rounded-[16px] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[16px] ${editablePalette.darkBg} ${editablePalette.darkText}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-[4px] border border-white/70 bg-transparent px-6 py-3 text-sm font-semibold tracking-[0.02em] text-[var(--slot4-on-accent)] transition duration-300 hover:border-[var(--slot4-accent)] hover:bg-[var(--slot4-accent)]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-[4px] border border-[var(--editable-border)] bg-transparent px-6 py-3 text-sm font-semibold tracking-[0.02em] text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-white`,
    accent: `inline-flex items-center justify-center gap-2 rounded-[4px] bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-110`,
    ghost: `inline-flex items-center justify-center gap-2 rounded-[4px] px-4 py-2 text-sm font-semibold text-[var(--slot4-muted-text)] transition duration-300 hover:text-[var(--slot4-page-text)]`,
  },
  badge: {
    pill: 'inline-flex items-center rounded-[4px] border border-[var(--editable-border)] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.16em]',
    accentPill: 'inline-flex items-center rounded-[4px] border border-[var(--slot4-accent)]/60 bg-[var(--slot4-accent-soft)] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--slot4-accent)]',
  },
  media: {
    frame: `relative overflow-hidden rounded-[16px] ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden ${editablePalette.mediaBg}`,
    ratio: 'aspect-[16/10]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1 hover:border-white/25',
    fade: 'transition duration-500 hover:opacity-80',
    zoom: 'transition duration-700 group-hover:scale-[1.035]',
  },
} as const

export const aiLayoutRules = [
  'Set the site palette in editableRootStyle first; downstream components consume the CSS variables.',
  'Use the PixoHub reference rhythm: dark hero, pale interlude, service grid, project/feed cards, process/trust, FAQ/contact/footer.',
  'Keep dynamic fetching and postHref routing intact.',
  'Keep user-facing task labels mapped through editableTaskLabel where task labels render.',
] as const
